### ISSUE TITLE
Enhancement Request: Add Icons, Random Profile Pictures, and UI Improvements  

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Ritwika-14/CoupEarn#1]
Title: Enhancement Request: Add Icons, Random Profile Pictures, and UI Improvements

Description:
Overview

This issue is raised to propose several enhancements to the current UI of our application, focusing on the review section and the contact us page. The suggested changes aim to improve the overall user experience and make the interface more visually appealing.
Changes Proposed
1. Review Section Enhancements
1.1 Company Icons

Add icons of respective companies next to user reviews to provide a visual representation of the companies being reviewed. This will help users quickly identify and associate reviews with specific companies.
1.2 Random Profile Pictures

Integrate a feature to display random profile pictures alongside user reviews. This addition will add a personal touch to the reviews and make the platform more engaging.
2. Contact Us Page
2.1 Enhanced Placeholders

Improve the placeholders in the contact form to provide clearer instructions and guidance to users. This will contribute to a more user-friendly experience when reaching out to our support team.
3. Home Page UI Changes
3.1 Overall Design Enhancement

Consider making subtle UI improvements on the home page to enhance the visual appeal and ensure a cohesive and modern look.
3.2 Call-to-Action Buttons

Evaluate the effectiveness of call-to-action buttons on the home page and make adjustments if necessary to improve user engagement.

 please ASSIGN this issue me 
 under  JWOC

**Comment by Ritwika-14** [comment]
I will start assigning u issues & accepting all the PR after the coding period starts on 15th JAN.
P.S- nice detailing! good work

**Comment by NaveenChandraAdhikari** [comment]
Ok

**Comment by Ritwika-14** [comment]
@NaveenChandraAdhikari Any issue raised before the Coding Phase (15th JAN) , will not be accepted in JWOC 2k24 and you won't be marked. Please delete this issue and do the same after 15th if you wish to get marked under JWOC.
