### ISSUE TITLE
Buy Coupons caption

### ISSUE THREAD

**Issue by Rishav9911** [Ritwika-14/CoupEarn#18]
**Describe the bug**
There is a slight error in buy coupon section where the cards captions have multiple Rs written on them making the line not make sense and confusing.

**Expected behavior**
Would like to remove the multiple Rs in all cards to make caption look right.

**Screenshots**
![Screenshot 2024-01-21 130919](https://github.com/Ritwika-14/CoupEarn/assets/133174630/7db4bfe9-8252-4b48-ba86-16ed87fd104f)

**Additional context**

**Contributing under some Open-Source Program?**
kindly assign me this under JWOC

**Comment by vishapraj** [comment]
@Ritwika-14 pls assign me this issue under "JWOC"

**Comment by vermaanurag1532** [comment]
please Assign it to me
