### ISSUE TITLE
Underline persists under 'Home' in navbar tabs despite switching to 'Buy' or other tabs.

### ISSUE THREAD

**Issue by thesri** [Ritwika-14/CoupEarn#2]
The underline under home in the nav bar is disturbing, other tabs switching feels like being in showing home though isnt , for this i can give hover and few effects to resolve this issue

**Comment by Ritwika-14** [comment]
I will start assigning u issues & accepting all the PR after the coding period starts on 15th JAN.
P.S- good issue raised.

**Comment by Ritwika-14** [comment]
@thesri Any issue raised before the Coding Phase (15th JAN) , will not be accepted in JWOC 2k24 and you won't be marked. Please do the same after 15th.

**Comment by thesri** [comment]
Okay

**Comment by thesri** [comment]
@Ritwika-14  can i work on this issue now?
