### ISSUE TITLE
Enhance Design and Functionality of 'Upload' and 'Browse' Buttons

### ISSUE THREAD

**Issue by Ritwika-14** [Ritwika-14/CoupEarn#3]
**Describe the bug**
The "Upload" and "Browse" buttons need improvement in terms of their appearance and/or functionality..

**To Reproduce**
1. Go to '/src/app.js'
2. Scroll down to '212' and see bug.

**Expected behavior**
Change the colour , make the borders round , add a hover effect etc.

**Screenshots**
![Screenshot (52)](https://github.com/Ritwika-14/CoupEarn/assets/119119223/543cbeb1-d7e7-406c-b31d-2f465001cfa1)

**Additional context**
WRITING A SAMPLE CODE
<button class="my-button">Click me</button> //add class name

.my-button {
    /* Adding a border radius of 10 pixels */
    border-radius: 10px;
    
    /* Additional styling for better visualization */
    padding: 10px 20px;
    font-size: 16px;
    background-color: #4CAF50;
    color: #fff;
    border: none;
    cursor: pointer;
}

/* Add hover effect */
.my-button:hover {
    background-color: #45a049;
}

**Comment by sanskritisahu21** [comment]
I'm eager to contribute to CoupEarn , and after exploring the issues, I'm interested in working on #3 : Enhance Design and functionality of 'upload' and 'browse' button.

**Comment by Ritwika-14** [comment]
@sanskritisahu21  I'll assign you after the coding period starts.

**Comment by ayesha-2101** [comment]
@Ritwika-14 I am a student from IIT Patna, and I am well-versed in web development. I am willing to work on this issue. Please assign it to me,

**Comment by Ritwika-14** [comment]
@ayesha-2101 @sanskritisahu21 Any comments made under an issue before the Coding Phase (15th JAN) , will not be accepted in JWOC 2k24 and you won't be marked. Please do the same after 15th.

**Comment by Anushkabh** [comment]
@Ritwika-14  i would like to  work for this , kindly assign

**Comment by sanskritisahu21** [comment]
I would like to work on this issue under JWOC. Please assign this issue to me.

**Comment by Anushkabh** [comment]
![Screenshot (98)](https://github.com/Ritwika-14/CoupEarn/assets/99523033/767e91bd-9c92-4ee2-a432-27438b78b4ff)
is this okay?

**Comment by Anushkabh** [comment]
kindly merge @Ritwika-14
