### ISSUE TITLE
Unset maximum expandable size of "add a review" text-area disrupts application UI.

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Ritwika-14/CoupEarn#6]
**Describe the bug**
When Add a review text box is expanded it disturbs the UI of the page

**Expected behavior**
Text area should have a maximum expandable width

**Screenshots**
<img width="960" alt="image" src="https://github.com/Ritwika-14/CoupEarn/assets/120127517/6211fc53-cee8-4860-a459-03f583c7adf8">

**Additional context**
I would love to work on this issue. Please assign this to me

**Comment by Ritwika-14** [comment]
If this issue is under JWoC please raise the issue after 15th else you won't be marked.
