### ISSUE TITLE
Content of the Page is not in order of the Navbar content

### ISSUE THREAD

**Issue by Divyanshgarg-04** [Ritwika-14/CoupEarn#7]
Navbar list include Home Buy Sell Review Contact  But the Page order of content is Home Sell Buy Review Contact.

That is the position of Sell and Buy in Navbar and Page are not in sync.

I would like to work on this issue.

**Comment by Ritwika-14** [comment]
@Divyanshgarg-04 Any issue raised before the Coding Phase (15th JAN) , will not be accepted in JWOC 2k24 and you won't be marked. Please delete this issue and do the same after 15th if you wish to get marked under JWOC.
